### ISSUE TITLE
Shorts now appear in video recommendations.

### ISSUE THREAD

**Issue by FlamingNinja42** [gijsdev/ublock-hide-yt-shorts#1]
See attached image.

![image](https://user-images.githubusercontent.com/3311655/235870947-6c694efd-5606-4e81-aa80-98c6290655c5.png)

**Comment by FlamingNinja42** [comment]
I found a filter which removes these:

##ytd-reel-shelf-renderer.ytd-item-section-renderer

**Comment by gijsdev** [comment]
I think that filter would remove other sections with about the same style as that Shorts section in your screenshot. I always try to use a selector which specifically mentions Shorts to avoid removing non-Shorts content.

For example this is the filter I used that should remove this section (but doesn't in this case):

`youtube.com##ytd-rich-section-renderer:has(#rich-shelf-header:has-text(Shorts))`

I will try to take a look if this section pops up in my feed. Thanks for the heads up!

**Comment by gijsdev** [comment]
I just found this section on m.youtube.com. I removed this one with:
`m.youtube.com##ytm-rich-section-renderer:has(.reel-shelf-title-wrapper:has-text(Shorts))`

So I suspect the following filter might work for the section you mentioned:
`youtube.com##ytd-rich-section-renderer:has(.reel-shelf-title-wrapper:has-text(Shorts))`

Can you confirm if this filter works or not? If so, I will update the filterlist.

**Comment by gijsdev** [comment]
I condensed the filter a bit and added it to the list. Thanks for your help!
