### ISSUE TITLE
FireTV firestick Roku ??

### ISSUE THREAD

**Issue by AdenaWilder** [gijsdev/ublock-hide-yt-shorts#22]
Sure would like to filter searches on the big screen OTT devices … FireTV firestick firecube Roku etc. … suggestions or just SOL ?

**Comment by jducifuentes** [comment]
That will be great!

**Comment by gijsdev** [comment]
I don't know anything about TVs. If you're able to use YouTube through a browser where you can install an adblocker on, then this repo should work (probably not because modern devices, yay!). Otherwise I don't know.
