### ISSUE TITLE
Hides shorts on history

### ISSUE THREAD

**Issue by xugro** [gijsdev/ublock-hide-yt-shorts#27]
The current setup hides the shorts I watched on my history page.
I still watch shorts on mobile and sometimes want to check the links in description from a computer but I need to disable ublock temporarily would appreciate if they weren't blocked on my history page.

**Comment by PanDabStudios** [comment]
Hello, you can do that by addin a `:not([href*="/feed/history"])` after every line that is not a comment, and that should do the trick.

Example:

`
! Hide all videos containing the phrase "#shorts"
www.youtube.com##ytd-grid-video-renderer:has(#video-title:has-text(/(^| )#Shorts?( |$)/i))
www.youtube.com##ytd-rich-item-renderer:has(#video-title:has-text(/(^| )#Shorts?( |$)/i))

becomes


! Hide all videos containing the phrase "#shorts"
www.youtube.com##ytd-grid-video-renderer:has(#video-title:has-text(/(^| )#Shorts?( |$)/i)):not([href*="/feed/history"])
www.youtube.com##ytd-rich-item-renderer:has(#video-title:has-text(/(^| )#Shorts?( |$)/i)):not([href*="/feed/history"])

` 

hope this helps!

**Comment by gijsdev** [comment]
Added a patch for this in https://github.com/gijsdev/ublock-hide-yt-shorts/commit/3f44bb1fb455bbff68ea9c8912eb4721c31aff63

It will be included in the next release.
