### ISSUE TITLE
Hides but...

### ISSUE THREAD

**Issue by Artur-Galis** [gijsdev/ublock-hide-yt-shorts#3]
It works but now youtube updated and it doesn't fill the place where there were a short 
![e1925bd3-647c-4306-8204-96b7e2d869f4](https://github.com/gijsdev/ublock-hide-yt-shorts/assets/81031994/47f83462-47c9-476f-b4ab-e503c8c98328)
![d22c8a8c-fa93-464a-8af3-4e3d0a92d4e9](https://github.com/gijsdev/ublock-hide-yt-shorts/assets/81031994/260d586c-6090-4e33-9c15-fbae786f4e96)

**Comment by gijsdev** [comment]
Since YouTube's small layout update it groups every row together and forces that row to take up the full width of the feed. 
This issue is unfortunately not something that's fixable with a uBlock filterlist.

If someone can prove me wrong on this, feel free to submit a pull request or send me in the right direction.

**Comment by Artur-Galis** [comment]
I fixed with this, not my code but saw it somewhere in Reddit

! YT Subscriptions Hide Shorts - Grid View
youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-rich-item-renderer [overlay-style="SHORTS"]:upward(ytd-rich-item-renderer)
! YT Subscriptions Row Fix to 6
youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-rich-grid-row:style(display:contents !important;)
youtube.com##ytd-browse[page-subtype="subscriptions"] #contents.ytd-rich-grid-row:style(display:contents !important;)
youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-rich-grid-renderer:style(--ytd-rich-grid-items-per-row: 6 !important;)
! YT Subscriptions Row Fix to 6 (Font Size fix)
youtube.com##ytd-browse[page-subtype="subscriptions"] #video-title.ytd-rich-grid-media:style(font-size: 1.4rem !important; line-height: 2rem !important;)
youtube.com##ytd-browse[page-subtype="subscriptions"] #metadata-line.ytd-video-meta-block:style(font-size: 1.2rem !important; line-height: 1.8rem !important;)
youtube.com##ytd-browse[page-subtype="subscriptions"] #video-title.ytd-rich-grid-slim-media:style(font-size: 1.4rem !important; line-height: 2rem !important;)

**Comment by gijsdev** [comment]
Oh, interesting. I will screw around with it and see if I can make it work without screwing up anything or changing the layout too much.

**Comment by gijsdev** [comment]
Fixed it in v1.6.0
