### ISSUE TITLE
[Feature request] Hide latest posts

### ISSUE THREAD

**Issue by Zane2b2t** [gijsdev/ublock-hide-yt-shorts#30]
![image](https://github.com/gijsdev/ublock-hide-yt-shorts/assets/88916121/9fefc413-8cc6-4730-be2b-514d9b61e247)

**Comment by gijsdev** [comment]
No, this list is for YouTube Shorts only.

The uBlock Origin subreddit has a snippet you can use for this: https://www.reddit.com/r/uBlockOrigin/wiki/solutions/youtube#wiki_homepage_posts
