### ISSUE TITLE
Shorts appear on notifications

### ISSUE THREAD

**Issue by Symmercy** [gijsdev/ublock-hide-yt-shorts#8]
I am sorry if this is not fixable or I have done something wrong, but when I opened notifications I got a youtube short there.
It happens kinda frequently and I hope this is fixable. 

This is an example of that:
![image](https://github.com/gijsdev/ublock-hide-yt-shorts/assets/91673840/6cbaa35c-5cd0-49ee-a51c-a48b1e6c09e4)

**Comment by gijsdev** [comment]
I don't think this is possible, but I will try to look into it to be 100% sure. I think I could hide the notification if it is a short, but I think the main problem would be the notification dot that appears when there are open notifications. I can't hide that based on the video types in the notifications.
